dahliaOS/pangolin_desktop

lib/main.dart
lib/window.dart

creates a dummy windows for tests

Add alpha window widget

---

lib/window/model.dart
lib/window/window.dart
lib/window_space.dart

the close button is working now, big yay!

add ability to close windows

---

lib/application.json

This is a fix of issues from #19

Fix authors in application.json

---

lib/application.json

Commit adds the Video Player plugin. 
Note to devs: Don't close this pull, I'm working on this branch again... thanks.

Video Player

---

lib/application.json

Very simple fix but your json is invalid. More pull requests to come!

Make json valid

---

.github/workflows/build.yml

I'll see if I can get automated APK builds to work

Introduce a debug APK builder

---

.github/workflows/web.yaml

This will implement a CI system for web demos. AFAIK you have to be on Chrome and a somewhat fast device to use it. I don't know, it's just the way Flutter's set up for some reason.

Add web build & deploy

---

lib/main.dart
lib/quick_settings.dart

Hi, I tried to improve the look and feel of the quicksettings.
I added a bit padding on the sides, increased the border radius, height and grid size and added bouncing physics.
I also moved the featureNotImplemented dialog into its own function to recude unnecessary code.
I changed the slider to two sliders, one for brightness and one for volume and made them slidable (but not actually working)
And btw it looks like I changed much in main.dart but thats only because I auto formatted the code
Preview:

Improved Quicksettings Look and Feel

---

lib/window/window.dart

Add hover effect to Titlebar buttons

---

.gitlab-ci.yml
dummy.txt

It's all finalized and ready for use.

Web builds

---

lib/localization/languages/de.json
lib/localization/languages/en.json
lib/localization/languages/fr.json
lib/localization/languages/hr.json
lib/localization/languages/pl.json
lib/localization/localization.dart
lib/main.dart
lib/quick_settings.dart
pubspec.yaml

Add more languages to the Language switch in Quicksettings.
Will be moved to Settings app soon.
Credits to the Translators.

Add more langauges to QS language switch

---

lib/searchbar.dart

Fix copyright year, also add more stuff to searchbar

Update searchbar.dart :) 

---

lib/localization/languages/nl.json

"app_web": "Browser",
"taskmanager_launch": "Lanceer", >> "taskmanager_launch": "Open",

better translation

---

lib/desktop/settings/pages/grid.dart
lib/desktop/settings/settings.dart

1. A new Settings Menu is implemented
2. Sidebar is now responsive and looks good on smaller screens and window sizes
3. Back Button added on the search screen

New menu and sidebar for settings

---

lib/desktop/taskbar_elements/launcher.dart
lib/desktop/taskbar_elements/launcher_apps_grid.dart
lib/desktop/taskbar_elements/launcher_chips_row.dart
lib/desktop/taskbar_elements/launcher_search_bar.dart

• auto-layout resizing – this means the launcher grid will resize appropriately on different screen sizes (see [examples](#screenshots) below)
• search bar also autoresizes its horizontal margins, and border radius to match (i.e. if no horizontal padding, no circle border radius bc that would look rather weird against a vertical edge)
• removed hover effect for launcher apps (can easily be reenabled if decided hover = good)
• separated grid launcher widgets out for better code readability, modularity, and reusability
• changed the row of chips in the launcher (all the 'test' rounded rects) to a separate widget and made it a horizontal ListView for narrower screens or more items
1. LauncherSearchBar
2. LauncherChipsRow
3. LauncherAppsGrid …

App launcher 📈

---

lib/widgets/app_launcher_button.dart

Fixed launcher apps hover

---

lib/applications/developer/developer.dart
lib/desktop/quicksettings/quick_settings.dart

* Please make sure you read and fill this template out entirely
* PRs that don't have the template filled out will be ignored
Switches commands in quicksettings and the developer settings app, to shut down via the init system rather than acpi powering off, to prevent corruption.
Fixes: N/A
Please tick the relevant option by putting an X inside the bracket

Switch shutdown commands

---

lib/desktop/taskbar/clock.dart

Please tick the relevant option by putting an X inside the bracket

Fix clock overflowing

---

lib/services/network_manager.dart
lib/utils/context_menus/context_menu_item.dart

Fix network manager icon and titlebar dialogue box overflow

---

lib/components/overlays/quick_settings/quick_settings_overlay.dart
lib/utils/data/app_list.dart
lib/utils/data/globals.dart
linux/flutter/generated_plugin_registrant.cc
linux/flutter/generated_plugins.cmake
pubspec.yaml

This merge includes:
* A fix that makes the files app work again, I pushed this on behalf of @larsb24 (thanks 💯 ) 
* Add the current Linux username to the quicksettings menu
Windows will pronounce itself as "Windows user"
and Web will pronounce itself as "dahliaOS Live user"

Double trouble: Make files app work again (Lars) and Add the current Linux username to quicksettings

---

lib/components/settings/pages/network/network.dart

Lars helped me a lot here,  thank you :)
This merge includes:
* Initial support for viewing networks in the settings app

Add wifi networks to the settings

---

lib/components/settings/pages/about.dart
lib/components/settings/pages/connections/connected_devices.dart
lib/components/settings/pages/customization/customization.dart
lib/components/settings/pages/developer_options.dart
lib/components/settings/pages/display.dart
lib/components/settings/pages/network/network.dart
lib/components/settings/widgets/list_tiles.dart
lib/components/settings/widgets/settings_card.dart
lib/components/settings/widgets/settings_page.dart
lib/components/taskbar/quick_settings.dart
lib/utils/theme/theme.dart

Settings: New SettingsCard Widget 

---

lib/components/overlays/account_overlay.dart
lib/components/overlays/launcher/compact_launcher_overlay.dart
lib/components/overlays/overview_overlay.dart
lib/components/overlays/power_overlay.dart
lib/components/overlays/quick_settings/widgets/qs_shortcut_button.dart
lib/components/overlays/quick_settings/widgets/qs_slider.dart
lib/components/overlays/quick_settings/widgets/qs_toggle_button.dart
lib/components/overlays/search/search_overlay.dart
lib/components/settings/widgets/settings_content_header.dart
lib/components/settings/widgets/taskbar_alignment_button.dart
lib/components/settings/widgets/theme_mode_button.dart
lib/components/taskbar/show_desktop.dart
lib/components/taskbar/taskbar_item.dart
lib/utils/context_menus/context_menu_item.dart
lib/utils/theme/theme.dart
lib/widgets/global/box/box_container.dart
lib/widgets/global/quick_button.dart
lib/widgets/quick_button.dart
macos/Podfile.lock
macos/Runner.xcodeproj/project.pbxproj

- This PR replaces the deprecated items with new replacements
Please tick the relevant option by putting an X inside the bracket

fix(global): deprecated

---

lib/components/overlays/quick_settings/widgets/qs_slider.dart
linux/flutter/generated_plugin_registrant.cc
linux/flutter/generated_plugins.cmake
macos/Flutter/GeneratedPluginRegistrant.swift
pubspec.yaml
windows/flutter/generated_plugin_registrant.cc
windows/flutter/generated_plugins.cmake

- This isn't much of an issue more of an improvement, on your website it shows the zenit UI slider for the quick settings, so I added it!
- new dependencies zenit_ui
Please tick the relevant option by putting an X inside the bracket

Zenit UI slider

---

lib/main.dart
lib/services/application.dart
lib/services/date_time.dart
lib/services/dbus.dart
lib/services/icon.dart
lib/services/langpacks.dart
lib/services/notifications.dart
lib/services/power.dart
lib/services/search.dart
lib/services/shell.dart
lib/services/tray.dart
lib/services/wm.dart
pubspec.yaml

Related to https://github.com/dahliaOS/shared/pull/3

pangolin: Adapt to new services api

---

lib/components/overlays/welcome_overlay.dart

We forgot to update the UI after the end of the animation.
https://github.com/dahliaOS/pangolin_desktop/assets/73116038/92fda555-98f3-4658-8cbe-5fe0269138e3

fix welcome overlay dismiss

---

.github/workflows/dart.yml

Add building process to the CI to test if the Desktop Actually compiles properly

[CI] Add build process to test compiling
